version: '3'

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - "redisdata:/data"
        networks:
            - "flasknet"
    web:
        build: .
        ports:
            - "5000:5000"
        networks:
            - "flasknet"
        depends_on:
            - "redis"
volumes:
    redisdata :
networks:
    flasknet :
